version = 0.1

[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "svange"
github_repo = "api-portal"
deployment_branch = "dev"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[api-portal-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::330659553592:role/aws-sam-cli-managed-api-porta-PipelineExecutionRole-6xtdRaDxmNtc"
cloudformation_execution_role = "arn:aws:iam::330659553592:role/aws-sam-cli-managed-api-p-CloudFormationExecutionRo-58LbeaLhtsWy"
artifacts_bucket = "aws-sam-cli-managed-api-portal-dev-artifactsbucket-kcx2dfjqjvxj"
image_repository = ""
region = "us-east-1"
