environment: prod
stack_name: api-portal-prod
enabled: true
update_timestamp: 2025-07-29 1851

# AWS Configuration - UPDATE THESE VALUES WHEN READY
aws:
  region: us-east-1
  account_id: "725925681078"
  pipeline_execution_role: arn:aws:iam::725925681078:role/aws-sam-cli-managed-augmentin-PipelineExecutionRole-nRqSDljFyJH0
  cloudformation_execution_role: arn:aws:iam::725925681078:role/aws-sam-cli-managed-augme-CloudFormationExecutionRo-ofPpaqgfKVmX
  artifacts_bucket: aws-sam-cli-managed-augmenting-int-artifactsbucket-mlzjl4yrtthm

# Stack Parameters
parameters:
  # S3 Buckets
  ArtifactsS3BucketName: augint-api-portal-prod-artifacts
  DevPortalSiteS3BucketName: augint-api-portal-prod-site
  
  # Cognito Configuration
  CognitoDomainNameOrPrefix: augint-portal
  CognitoIdentityPoolName: DevPortalIdentityPool-prod
  
  # Admin Configuration
  DevPortalAdminEmail: samuelvange@gmail.com
  
  # Table Names (optional - defaults exist)
  DevPortalCustomersTableName: DevPortalCustomers-prod
  DevPortalFeedbackTableName: DevPortalFeedback-prod
  DevPortalPreLoginAccountsTableName: DevPortalPreLoginAccounts-prod
  
  # Static Asset Configuration
  StaticAssetRebuildMode: overwrite-content
  StaticAssetRebuildToken: prod-${GITHUB_SHA}
  EdgeLambdaRebuildToken: prod-${GITHUB_SHA}
  
  # Custom Domain Configuration - FILL THESE OUT
  CustomDomainName: "portal.augmentingintegrations.com"
  HostedZoneName: "augmentingintegrations.com"
  CustomDomainNameAcmCertArn: "arn:aws:acm:us-east-1:725925681078:certificate/174fee79-97ee-446f-b23f-d538310820be"
  UseRoute53Nameservers: "true"